/*
    3.56 ◆◆
    Consider the following assembly code:

    x at %ebp+8, n at %ebp+12

        movl 8(%ebp), %esi      # Copy x into %esi
        movl 12(%ebp), %ebx     # Copy n into %ebx
        movl $-1, %edi          # -1 at %edi
        movl $1, %edx           # 1 at %edx
    .L2:
        movl %edx, %eax         # Copy %edx {1} into %eax
        andl %esi, %eax         # [x & 0x1] into %eax
        xorl %eax, %edi         # [[x & 0x1] or -1] into %edi
        movl %ebx, %ecx         # Copy n into %ecx
        sall %cl, %edx          # shifts %edx left by %cl bits. (%cl is the low byte of %ecx)
        testl %edx, %edx        # Tests whether that shift zeroed out %edx
        jne .L2                 #
        movl %edi, %eax

    The preceding code was generated by compiling C code that had the following
    overall form:

        int loop(int x, int n)
        {
            int result = ;
            int mask;
            for (mask = ; mask ; mask = )
            {
                result ^= ;
            }
            return result;
        }

    Your task is to fill in the missing parts of the C code to get a program equivalent
    to the generated assembly code. Recall that the result of the function is returned
    in register %eax. You will find it helpful to examine the assembly code before,
    during, and after the loop to form a consistent mapping between the registers and
    the program variables.
    A. Which registers hold program values x, n, result, and mask?
    B. What are the initial values of result and mask?
    C. What is the test condition for mask?
    D. How does mask get updated?
    E. How does result get updated?
    F. Fill in all the missing parts of the C code.

*/

#include <stdio.h>


int loop(int x, int n)
{
    int result = -1;
    int mask;
    for (mask = 1; mask != 0; mask <<= n)
    {
        result ^= (mask & x);
    }
    return result;
}

/*
A. Which registers hold program values x, n, result, and mask?

    x is in register %esi
    n is in register %ebx
    result is in register %edi
    mask is in register %edx

B. What are the initial values of result and mask?

    Initial value for result is -1, initial value for mask is 1

C. What is the test condition for mask? (5pts.)

    mask != 0

D. How does mask get updated? (5pts.)

   mask updates whenever %edx is shifted to the left by n bits

E. How does result get updated?
   result is updated when bitwise masked on  x and the result is XORed with
   result.
*/
